--local Anno = require("lua/anno_interface");
--local async = require("lua/utils_async");
--local shipCmd = require("lua/mod_ship_cmd");
--local objectAccessor = require("lua/anno_object_accessor");
--local logger = require("lua/utils_logger");
--
--
--local function Ship_Name_StoreCmdInfo(oid, dst)
--    local SEPARATOR = "|";
--
--    local x = dst.x;
--    local y = dst.y;
--    local areaID = dst.area_id;
--
--    local name = Anno.Ship_Name_Get(oid);
--    local sep = string.find(name, SEPARATOR);
--    if sep then
--        name = string.sub(name, 1, sep - 1);
--    end
--
--    local info = name .. SEPARATOR ..
--            tostring(x) .. SEPARATOR ..
--            tostring(y) .. SEPARATOR ..
--            tostring(areaID);
--    Anno.Ship_Name_Set(oid, info);
--end
--
--function TradeExecutor.Ship_Name_FetchCmdInfo(oid)
--    local SEPARATOR = "|";
--
--    local name = Anno.Ship_Name_Get(oid);
--    local parts = {};
--    for part in string.gmatch(name, "([^" .. SEPARATOR .. "]+)") do
--        table.insert(parts, part);
--    end
--
--    if #parts < 4 then
--        return nil; -- No info packed
--    end
--
--    local info = {
--        name = parts[1],
--        x = tonumber(parts[2]),
--        y = tonumber(parts[3]),
--        area_id = tonumber(parts[4])
--    };
--
--    return info;
--end
--
